# Generated by Django 3.2.9 on 2021-11-19 11:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('country', models.CharField(max_length=45)),
                ('city', models.CharField(max_length=45)),
                ('street', models.CharField(max_length=45)),
                ('contact_phone', models.CharField(max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=45)),
                ('password', models.CharField(max_length=45)),
                ('role', models.CharField(max_length=45)),
                ('email', models.EmailField(max_length=45)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=45)),
                ('lastname', models.CharField(max_length=45)),
                ('pesel', models.CharField(max_length=11)),
                ('country', models.CharField(max_length=45)),
                ('city', models.CharField(max_length=45)),
                ('street', models.CharField(max_length=45)),
                ('house_number', models.CharField(max_length=5)),
                ('apartament_number', models.CharField(max_length=10)),
                ('zip_code', models.CharField(max_length=6)),
                ('phone_number', models.CharField(max_length=12)),
                ('gender', models.CharField(max_length=45)),
                ('is_vaccinated', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Vaccine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacturer', models.IntegerField()),
                ('expiration_date', models.DateTimeField()),
                ('name', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('took_place', models.BooleanField()),
                ('id_facility', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='vaccinationProject.facility')),
                ('id_patient', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='vaccinationProject.user')),
                ('id_vaccine', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='vaccinationProject.vaccine')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='id_user_details',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='vaccinationProject.userdetails'),
        ),
    ]
