# Generated by Django 4.0.1 on 2022-01-12 17:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('country', models.CharField(max_length=45)),
                ('city', models.CharField(max_length=45)),
                ('street', models.CharField(max_length=45)),
                ('contact_phone', models.CharField(max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=45)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=45)),
                ('lastname', models.CharField(max_length=45)),
                ('pesel', models.CharField(max_length=11)),
                ('date_of_birth', models.DateField(default='1500-01-01')),
                ('country', models.CharField(max_length=45)),
                ('city', models.CharField(max_length=45)),
                ('street', models.CharField(max_length=45)),
                ('house_number', models.CharField(max_length=5)),
                ('apartament_number', models.CharField(max_length=10)),
                ('zip_code', models.CharField(max_length=6)),
                ('phone_number', models.CharField(max_length=12)),
                ('gender', models.CharField(max_length=45)),
                ('is_vaccinated', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Vaccine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacturer', models.CharField(max_length=55)),
                ('expiration_date', models.DateField()),
                ('name', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_date', models.DateField(blank=True, default='1000-01-01')),
                ('visit_time', models.TimeField(blank=True, default='00:00:00')),
                ('took_place', models.BooleanField(default=0)),
                ('id_facility', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='visit', to='vaccinationProject.facility')),
                ('id_patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='visit', to='vaccinationProject.user')),
                ('id_vaccine', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='visit', to='vaccinationProject.vaccine')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='id_user_details',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user', to='vaccinationProject.userdetails'),
        ),
        migrations.AddField(
            model_name='user',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
