# Generated by Django 3.2.9 on 2022-01-05 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaccinationProject', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='date_of_birth',
            field=models.DateField(default='1500-01-01'),
        ),
        migrations.AddField(
            model_name='visit',
            name='visit_date',
            field=models.DateTimeField(blank=True, default='1000-01-01 00:00:00'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='took_place',
            field=models.BooleanField(default=False),
        ),
    ]
