# Generated by Django 3.2.9 on 2022-01-05 19:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vaccinationProject', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='date_of_birth',
            field=models.DateField(default='1500-01-01'),
        ),
        migrations.AddField(
            model_name='visit',
            name='visit_date',
            field=models.DateTimeField(blank=True, default='1000-01-01 00:00:00'),
        ),
        migrations.AlterField(
            model_name='user',
            name='id_user_details',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user', to='vaccinationProject.userdetails'),
        ),
        migrations.AlterField(
            model_name='vaccine',
            name='expiration_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='vaccine',
            name='manufacturer',
            field=models.CharField(max_length=55),
        ),
        migrations.AlterField(
            model_name='visit',
            name='id_facility',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='visit', to='vaccinationProject.facility'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='id_patient',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='visit', to='vaccinationProject.user'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='id_vaccine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='visit', to='vaccinationProject.vaccine'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='took_place',
            field=models.BooleanField(default=0),
        ),
    ]
